apiVersion: scheduler.config.project.io/v1alpha1
kind: SchedulerConfiguration
ClientConnection:
  Kubeconfig: ""
  Burst: 100
  QPS: 50
DguestInitialBackoffSeconds: 1
DguestMaxBackoffSeconds: 10
EnableContentionProfiling: true
EnableProfiling: true
HealthzBindAddress: ""
LeaderElection:
  LeaderElect: false
  LeaseDuration: 15s
  RenewDeadline: 10s
  ResourceLock: leases
  ResourceName: dguest-scheduler
  ResourceNamespace: dguest-ns
  RetryPeriod: 2s
MetricsBindAddress: ""
Parallelism: 16
Profiles:
  - SchedulerName: ac-scheduler
    Plugins:
      Filter:
        Enabled:
          - Name: NodeAvailability
      Score:
        Enabled:
          - Name: NodeAvailability
      MultiPoint:
        Enabled:
          - Name: PrioritySort
          - Name: NodeAvailability
          - Name: DefaultBinder
