apiVersion: scheduler.project.io/v1alpha1
kind: Food
metadata:
  labels:
    version: v1
    cuisine: example
    area: af
  name: example2-food2
  namespace: food
spec:
  unschedulable: false
status:
  allocatable:
    cpu: "4"
    bandwidth: "40"
    memory: 4025084Ki
    gate: "110"
  capacity:
    cpu: "5"
    bandwidth: "60"
    memory: 5025084Ki
    gate: "110"
  foodInfo:
    version: v1
    coreRunNode: node1
    items:
      - namespace: af-ms3
        name: af-ms3-p1
        phase: Good
      - namespace: af-ms4
        name: af-ms4-p1
        phase: Good

