//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	"dguest-scheduler/pkg/scheduler/apis/config"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&config.DefaultPreemptionArgs{}, func(obj interface{}) { SetObjectDefaults_DefaultPreemptionArgs(obj.(*config.DefaultPreemptionArgs)) })
	//scheme.AddTypeDefaultingFunc(&config.InterDguestAffinityArgs{}, func(obj interface{}) { SetObjectDefaults_InterDguestAffinityArgs(obj.(*config.InterDguestAffinityArgs)) })
	scheme.AddTypeDefaultingFunc(&config.SchedulerConfiguration{}, func(obj interface{}) {
		SetObjectDefaults_KubeSchedulerConfiguration(obj.(*config.SchedulerConfiguration))
	})
	//scheme.AddTypeDefaultingFunc(&config.FoodResourcesBalancedAllocationArgs{}, func(obj interface{}) {
	//	SetObjectDefaults_FoodResourcesBalancedAllocationArgs(obj.(*config.FoodResourcesBalancedAllocationArgs))
	//})
	//scheme.AddTypeDefaultingFunc(&config.FoodResourcesFitArgs{}, func(obj interface{}) { SetObjectDefaults_FoodResourcesFitArgs(obj.(*config.FoodResourcesFitArgs)) })
	//scheme.AddTypeDefaultingFunc(&config.DguestTopologySpreadArgs{}, func(obj interface{}) { SetObjectDefaults_DguestTopologySpreadArgs(obj.(*config.DguestTopologySpreadArgs)) })
	//scheme.AddTypeDefaultingFunc(&config.VolumeBindingArgs{}, func(obj interface{}) { SetObjectDefaults_VolumeBindingArgs(obj.(*config.VolumeBindingArgs)) })
	return nil
}

func SetObjectDefaults_DefaultPreemptionArgs(in *config.DefaultPreemptionArgs) {
	SetDefaults_DefaultPreemptionArgs(in)
}

func SetObjectDefaults_InterDguestAffinityArgs(in *config.InterDguestAffinityArgs) {
	SetDefaults_InterDguestAffinityArgs(in)
}

func SetObjectDefaults_KubeSchedulerConfiguration(in *config.SchedulerConfiguration) {
	SetDefaults_KubeSchedulerConfiguration(in)
}

func SetObjectDefaults_FoodResourcesBalancedAllocationArgs(in *config.FoodResourcesBalancedAllocationArgs) {
	SetDefaults_FoodResourcesBalancedAllocationArgs(in)
}

func SetObjectDefaults_FoodResourcesFitArgs(in *config.FoodResourcesFitArgs) {
	SetDefaults_FoodResourcesFitArgs(in)
}

func SetObjectDefaults_DguestTopologySpreadArgs(in *config.DguestTopologySpreadArgs) {
	SetDefaults_DguestTopologySpreadArgs(in)
}

func SetObjectDefaults_VolumeBindingArgs(in *config.VolumeBindingArgs) {
	SetDefaults_VolumeBindingArgs(in)
}
